/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary': '#472a00',
        tertiary: '#8fd5ff',
        'secondary-fixed': '#c4e7ff',
        'surface-bright': '#31394d',
        secondary: '#7bd0ff',
        'on-secondary-container': '#00374d',
        primary: '#ffc174',
        'inverse-primary': '#855300',
        'surface-container-highest': '#2d3449',
        'tertiary-fixed': '#c5e7ff',
        'on-primary-fixed-variant': '#653e00',
        'error-container': '#93000a',
        'primary-fixed-dim': '#ffb95f',
        'surface-variant': '#2d3449',
        'on-tertiary': '#00344a',
        outline: '#a08e7a',
        surface: '#0b1326',
        error: '#ffb4ab',
        'tertiary-fixed-dim': '#7fd0ff',
        'on-tertiary-container': '#004966',
        'primary-container': '#f59e0b',
        'surface-container-high': '#222a3d',
        'on-surface-variant': '#d8c3ad',
        background: '#0b1326',
        'surface-container': '#171f33',
        'surface-container-lowest': '#060e20',
        'surface-tint': '#ffb95f',
        'primary-fixed': '#ffddb8',
        'on-tertiary-fixed': '#001e2d',
        'tertiary-container': '#1abdff',
        'on-secondary-fixed-variant': '#004c69',
        'on-error': '#690005',
        'on-surface': '#dae2fd',
        'on-tertiary-fixed-variant': '#004c6a',
        'inverse-on-surface': '#283044',
        'surface-dim': '#0b1326',
        'surface-container-low': '#131b2e',
        'on-secondary': '#00354a',
        'outline-variant': '#534434',
        'secondary-container': '#00a6e0',
        'on-background': '#dae2fd',
        'on-secondary-fixed': '#001e2c',
        'secondary-fixed-dim': '#7bd0ff',
        'inverse-surface': '#dae2fd',
        'on-primary-container': '#613b00',
        'on-error-container': '#ffdad6',
        'on-primary-fixed': '#2a1700',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'gutter-md': '1.5rem',
        'gutter-lg': '2rem',
        'space-lg': '1.5rem',
        'space-xs': '0.25rem',
        'margin-lg': '3rem',
        'space-md': '1rem',
        margin: '1rem',
        gutter: '1rem',
        'space-xl': '2.5rem',
        'space-sm': '0.5rem',
        'margin-md': '1.5rem',
      },
      fontFamily: {
        'label-xs': ['JetBrains Mono'],
        'body-sm': ['Geist'],
        'label-telemetry': ['JetBrains Mono'],
        'headline-lg-mobile': ['Space Grotesk'],
        'display-lg': ['Space Grotesk'],
        'body-lg': ['Geist'],
        'label-md': ['JetBrains Mono'],
        'headline-md': ['Space Grotesk'],
        'body-md': ['Geist'],
        'display-lg-mobile': ['Space Grotesk'],
        'headline-sm': ['Space Grotesk'],
        'headline-lg': ['Space Grotesk'],
      },
      fontSize: {
        'label-xs': ['10px', { lineHeight: '14px', fontWeight: '500' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'label-telemetry': ['15px', { lineHeight: '20px', fontWeight: '600' }],
        'headline-lg-mobile': ['26px', { lineHeight: '34px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-md': ['22px', { lineHeight: '30px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', fontWeight: '700' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
