ALTER TABLE bikes DROP COLUMN IF EXISTS vin;
ALTER TABLE bikes DROP COLUMN IF EXISTS category;
ALTER TABLE bikes DROP COLUMN IF EXISTS user_id;
DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
DROP TABLE IF EXISTS users;
